//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Group_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_Group_Master()
        {
            this.Client_Master = new HashSet<Client_Master>();
        }
    
        public int Hospital_Group_Id { get; set; }
        public string Hospital_Group_Name { get; set; }
        public string Hospital_Group_Code { get; set; }
        public int Created_By_User { get; set; }
        public int Updated_By_User { get; set; }
        public System.DateTime Create_Dt_Time { get; set; }
        public System.DateTime Update_Dt_Time { get; set; }
        public decimal Commission_Percentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Master> Client_Master { get; set; }
    }
}
