//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Type_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact_Type_Master()
        {
            this.Contact_Sub_Type_Master = new HashSet<Contact_Sub_Type_Master>();
            this.Contact_Master = new HashSet<Contact_Master>();
        }
    
        public int Contact_Type_Id { get; set; }
        public string Contact_Type { get; set; }
        public Nullable<int> Created_By_User { get; set; }
        public Nullable<int> Updated_By_User { get; set; }
        public Nullable<System.DateTime> Create_Dt_Time { get; set; }
        public Nullable<System.DateTime> Update_Dt_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Sub_Type_Master> Contact_Sub_Type_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Master> Contact_Master { get; set; }
    }
}
