//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Status
    {
        public int Status_Id { get; set; }
        public int Patient_Id { get; set; }
        public int Collector_Id { get; set; }
        public int Disposition_Id { get; set; }
        public Nullable<System.DateTime> Contact_Date { get; set; }
        public string Method_Of_Contact { get; set; }
        public string Valid_Contact_Number { get; set; }
        public string Valid_Contact_Number_Type { get; set; }
        public decimal? Current_Balance { get; set; }
        public string Notes { get; set; }
        public bool IsLatest { get; set; }
        public Nullable<int> Created_By_User { get; set; }
        public Nullable<int> Updated_By_User { get; set; }
        public Nullable<System.DateTime> Create_Dt_Time { get; set; }
        public Nullable<System.DateTime> Uppdate_Dt_Time { get; set; }
        public Nullable<System.DateTime> Last_Payment_Date { get; set; }
        public Nullable<decimal> Last_Payment_Amount { get; set; }
        public Nullable<decimal> Total_Paid_Amount { get; set; }

        public virtual Contact_Master Contact_Master { get; set; }
        public virtual Disposition_Master Disposition_Master { get; set; }
        public virtual Patient_Master Patient_Master { get; set; }
    }
}
