//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Receivables_Info
    {
        public int Patient_Id { get; set; }
        public string Patient_Type_Code { get; set; }
        public int Payer_Id { get; set; }
        public Nullable<int> Created_By_User { get; set; }
        public Nullable<int> Updated_By_User { get; set; }
        public Nullable<System.DateTime> Create_Dt_Time { get; set; }
        public Nullable<System.DateTime> Update_Dt_Time { get; set; }
    
        public virtual Patient_Master Patient_Master { get; set; }
        public virtual Patient_Type_Master Patient_Type_Master { get; set; }
        public virtual Payer_Master Payer_Master { get; set; }
    }
}
