//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Treatments
    {
        public int Patient_Treatments_Id { get; set; }
        public int Patient_Id { get; set; }
        public Nullable<System.DateTime> Treatment_Date { get; set; }
        public string Treatment_Code { get; set; }
        public string Treatment_Description { get; set; }
        public decimal Total_Charges { get; set; }
        public Nullable<int> Created_By_User { get; set; }
        public Nullable<int> Updated_By_User { get; set; }
        public Nullable<System.DateTime> Create_Dt_Time { get; set; }
        public Nullable<System.DateTime> Update_Dt_Time { get; set; }

        public virtual Patient_Master Patient_Master { get; set; }
    }
}
