//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payments_Id { get; set; }
        public int Patient_Id { get; set; }
        public int? Payment_Index { get; set; }
        public string Payment_Type { get; set; }
        public decimal? Payment_Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<System.DateTime> Payment_Post_Date { get; set; }
        public string Payment_Details { get; set; }
        public Nullable<int> Created_By_User { get; set; }
        public Nullable<int> Updated_By_User { get; set; }
        public Nullable<System.DateTime> Create_Dt_Time { get; set; }
        public Nullable<System.DateTime> Update_Dt_Time { get; set; }
        public bool IsActive { get; set; }
        public decimal? Revenue { get; set; }
    
        public virtual Patient_Master Patient_Master { get; set; }
    }
}
